version: "3.8"
services:
  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  sql:
    extends:
      file: docker-compose.yaml
      service: sql

  redisbrowser:
    image: rediscommander/redis-commander
    networks:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - sql
    ports:
      - "8082:80"
      - "8445:443"
    env_file:
      - app.env
    depends_on:
      - sql

networks:
  redis: 
  sql: