version: "3.8"
services:
  redis:
    image: redis:alpine
    networks:
      redis:
        aliases:
          - redis
    restart: unless-stopped
  
  sql:
    image: postgres:alpine
    networks:
      sql:
        aliases:
          - sql
    env_file:
      - app.env
  
  api:
    build: 
      context: .
      args:
        envtype: dev
    ports:
      - "8080:8000"
    expose:
      - 8000/tcp
    volumes:
      - ./:/usr/src/app
    networks:
      redis:
        aliases: 
          - api
      sql:
        aliases:
          - api
      web:
        aliases:
          - api
    env_file:
      - app.env
    depends_on:
      - redis
      - sql

networks:
  redis: 
  sql:
  web:
