# permissions for end users to edit factorioservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: factorioserver-editor-role
rules:
- apiGroups:
  - fsm.xenrelay.com
  resources:
  - factorioservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fsm.xenrelay.com
  resources:
  - factorioservers/status
  verbs:
  - get
