# permissions for end users to view factorioservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: factorioserver-viewer-role
rules:
- apiGroups:
  - fsm.xenrelay.com
  resources:
  - factorioservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fsm.xenrelay.com
  resources:
  - factorioservers/status
  verbs:
  - get
