name: React CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: action-yarn
        uses: comchangs/action-yarn@v0.1-beta
        with:
          args: "cd frontend; yarn install; yarn build; yarn test;"

